export const orderJson = {
    "order_nbr": "12345",
    "order_date": "2025-02-22",
    "marketplace": null,
    "shipto_name": "Kyle Ward",
    "tracking_callback": "callbacktest.com",
    "shipto_company": "",
    "shipto_address_1": "100 Mall Parkway Suite 210",
    "shipto_address_2": "",
    "shipto_city": "Wentzville",
    "shipto_state": "MO",
    "shipto_zip": "63385",
    "shipto_country": "US",
    "shipto_phone": "+1111111111",
    "ship_method": "economy",
    "notes": "",
    "gift_message": "",
    "custom_pack_slip": null,
    "shipping_label": null,
    "reprint_code": "",
    "handling": "",
    "items": [
        {
            "name": "prod name",
            "item_name_packslip": "Personalized Baby Name Bib | Pacific - block",
            "item_id": "435449573",
            "item_qty": 1,
            "ptg_part_number": "KK1609",
            "orig_part_number": "AUTOBIBpacific-block",
            "design_color": "block",
            "artwork_url_1": "https://www.picthegift.com/rshared/ssc/i/riq/6925486/f/f/t/0/0/logo.svg",
            "artwork_url_2": "",
            "personalization_text_1": "Ward",
            "personalization_text_2": "Kyle",
  
        },
        {
            "name": "prod name",
            "item_name_packslip": "Personalized Baby Name Swaddle Blanket - Emerald / Block+Script",
            "item_id": "435449572",
            "item_qty": 2,
            "ptg_part_number": "SWLG01_CL",
            "orig_part_number": "AUTOSWDLS-Lemerald/blockscript",
            "design_color": "Lemerald/blockscript",
            "artwork_url_1": "https://www.picthegift.com/rshared/ssc/i/riq/6925486/f/f/t/0/0/logo.svg",
            "artwork_url_2": "",
            "personalization_text_1": "Kyle1",
            "personalization_text_2": "ward2",
        },
        {
            "name": "prod name",
            "item_name_packslip": "Paw Prints and Pink Gingham Personalized Pet Mat / Pet Name / Girl Cat Dog Bowl Mat / Pet Supplies / Farmhouse Style Watercolor Gingham",
            "item_id": "435433954",
            "item_qty": 5,
            "ptg_part_number": "PM1424",
            "orig_part_number": "PM1424",
            "design_color": null,
            "artwork_url_1": "https://www.picthegift.com/rshared/ssc/i/riq/6925486/f/f/t/0/0/logo.svg",
            "artwork_url_2": "",
            "personalization_text_1": "Maisy",
            "personalization_text_2": "",
        },
        {
            "name": "prod name",
            "item_name_packslip": "Personalized Baby Name Swaddle Blanket - Emerald / Block+Script",
            "item_id": "435449572",
            "item_qty": 3,
            "ptg_part_number": "SWLG01_CL",
            "orig_part_number": "AUTOSWDLS-Lemerald/blockscript",
            "design_color": "Lemerald/blockscript",
            "artwork_url_1": "https://www.picthegift.com/rshared/ssc/i/riq/6925486/f/f/t/0/0/logo.svg",
            "artwork_url_2": "",
            "personalization_text_1": "Kyle2",
            "personalization_text_2": "Ward2",
        },
        {
            "name": "prod name",
            "item_name_packslip": "Personalized Baby Name Swaddle Blanket - Emerald / Block+Script",
            "item_id": "435449572",
            "item_qty": 1,
            "ptg_part_number": "SWLG01_CL",
            "orig_part_number": "AUTOSWDLS-Lemerald/blockscript",
            "design_color": "Lemerald/blockscript",
            "artwork_url_1": "https://www.picthegift.com/rshared/ssc/i/riq/6925486/f/f/t/0/0/logo.svg",
            "artwork_url_2": "",
            "personalization_text_1": "Kyle3",
            "personalization_text_2": "Ward3",
        }
    ],
    "returnto_name": "",
    "returnto_address1": "",
    "returnto_address2": "",
    "returnto_city": "",
    "returnto_state": "",
    "returnto_postal_code": "",
    "returnto_country": "US",
    "returnto_phone": ""
}